# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2d83973f-dcda-41a1-8fae-4e63215f47cb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2d83973f-dcda-41a1-8fae-4e63215f47cb".device = "/dev/disk/by-uuid/2d83973f-dcda-41a1-8fae-4e63215f47cb";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8CCD-B035";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-6689efc2-d07e-4b76-b94d-0a5a5287abdc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
